Creacion de HomeScreen y providers agregados
OscarOcomatl/cocktail_app pull request #1
Opened 2024-09-12 23:54 UTC by operezcc

2024-09-13 18:36 UTC, operezcc commented
Espero que se acepte el pull request de un pequeño avance que realicé 👍

2024-09-13 20:22 UTC, OscarOcomatl commented on lib/providers/cocktails_provider.dart
> -    // final url = Uri.https(_baseUrl, endpoint);
No borres estos comentarios porque son importantes

2024-09-13 21:06 UTC, OscarOcomatl requested changes
Porfavor no borres comentarios ya que sirven para guiarse

2024-09-17 17:30 UTC, operezcc commented
@OscarOcomatl realicé los cambios solicitados

2024-09-17 17:37 UTC, OscarOcomatl approved these changes
Perfecto @operezcc parece que todo bien

2024-09-17 17:42 UTC, merged